// Generated by Wrangler on Thu Sep 05 2024 16:13:26 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types --experimental-include-runtime`

interface Env {
	PUBLIC_KEY: string;
	TOKEN: string;
	CLIENT_ID: string;
	DB: D1Database;
}
